# Generated by Django 5.0.2 on 2024-06-12 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office_emp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='dept',
            new_name='department',
        ),
    ]
